#Github Repo Access Config
Github:
  UserInfo:
    repoOwner: 'sean-keisuke'
    repoName: 'TestRepo'
    token: 852dfabd9892ef8c3ad20788146ea10d0fbe74ef
  IssueReport1:
    title: "Sample title from HelloWorld "
    body: "Sample body, I wanna get all kind of shit done. "
    bug: 
      - bug
      - question
  IssueReport2:
    title: "Sample title2 from HelloWorld "
    body: "Sample body, I wanna get all kind of shit done. "
    bug: 
      - bug
      - question
  IssueReport3:
    title: "Sample title3 from HelloWorld "
    body: "Sample body, I wanna get all kind of shit done. "
    bug: 
      - bug
      - question
  IssueReport4:
    title: "Sample title4 from HelloWorld "
    body: "Sample body, I wanna get all kind of shit done. "
    bug: 
      - bug
      - question
